### PR TITLE
Update the UPF doc links

### PR DESCRIPTION
**Pull request by unkcpz**
Hi @ltalirz, I am starting to use this repo to verify the UPF files and try to add more to schema for example the optional field  'label of orbital' which is required by hubbard +U. As I know json schema support 'mandatory' and 'optional' fields, I guess it is also true for XML schema. 

Anyway, I think this PR can be a good start for more contribution from my side. Cheers!

### CODE REVIEW

**Comment by ltalirz** [comment]
Thanks @unkcpz , please note however that this repository was created by me a long time ago, based on a text document describing the UPF that is no longer present on the QE web site.

There is a more up-to-date https://github.com/QEF/qeschemas repository on the QEF github org as well as this one https://github.com/QEF/qexsd .

I opened two issues on https://github.com/QEF/qeschemas that never received a reply

In my view it would be very impactful if:
 * the XML schema definitions of the UPF were consolidated into a single repository
 * this repository would contain auto-generated documentation created from the schema definition
 * the official UPF documentation would point developers to that repository

I don't think this is a lot of work, and it will avoid confusion going forward.

Pinging @mbercx and @pietrodelugas as well in case they can provide guidance on this

**Comment by pietrodelugas** [comment]
Hello @ltalirz 
the pseudopotentials  in QE have a mini-website [pseudopotentials.quantum-espresso.org](https://pseudopotentials.quantum-espresso.org) of their own. The UPF documentation is still there, last link of the left pannel. 

I followed some of your suggestions  (thanks) about qeschemas and try to implement the otherd asap.  

 As the merge requests  people working on schemas are just a few, so there are no strict rules on how to do that. The way I do it usually it to add a schema with new content in the test_schema directory,,  in the PR we can discuss about the changes. Then one should implement the read/write part in the main qe repository, once is ready we just create e new version of the schema.  Most of the time I do it alone or with the help of some interested person  (e.g.  Iurii from EPFL for the new format of the Hubbard section). So there is not a cleat-cut procedure.  Sorry for the delayed response. 
 
Pietro 

P.S. pseudopotential schema is on the PP directory of the qeschemas repo. read and write are already implemented. It is slightly different from UPF v2.  But the main differences are quite negligible:

 *  tag names from capital to lower case
 *  projector indexes out of the tag name and put as attributes 
 * relativistic information has been moved as attributes of the projectors.

**Comment by ltalirz** [comment]
Thanks a lot for the feedback, Pietro, this already clears up a few questions.

I've added a PR to qeschemas to provide some extra guidance for new users https://github.com/QEF/qeschemas/pull/10

As far as the UPF schema is concerned, would you welcome merging the content of https://github.com/ltalirz/upf-schema into the UPF schema on https://github.com/QEF/qeschemas? This would include both updating/merging the schemas [1], as well as the addition of the script to automatically produce a documentation of the format from the schema.

@unkcpz would you perhaps be interested in giving this a try?

Eventually, https://pseudopotentials.quantum-espresso.org/home/unified-pseudopotential-format could then be replaced by the documentation that is autogenerated from the schema, reducing maintenance burden and making sure there is no discrepancy between documentation and implementation.

[1] I guess the update from v0.99 to UPF v2 is long overdue (UPF v2.0.1 was already out when I created this repository in 2013).

**Comment by pietrodelugas** [comment]
Anything that may help documentation is warmly welcome. 
At the the moment UPF v2 and the upf with schema coexist, and are completely equivalent, and as I wrote there are just small differences.  The changes were mostly aimed at easing the preparation of the XSD schema, such as the elimination of the random tag names for the beta projectors.  At a first glance, the documentation is easily transferable to the new schema.

**Comment by unkcpz** [comment]
Thanks both @ltalirz @pietrodelugas and I am happy to work on this. Just to make it clear, the first step is to merging schema of this repository to https://github.com/QEF/qeschemas, then @pietrodelugas will take care of update the https://pseudopotentials.quantum-espresso.org/home/unified-pseudopotential-format, correct?

**Pull request merged**
